version: 2

updates:
  # Configuration for Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: 'daily'

    ignore:
      - dependency-name: 'ruby:3.1.0-slim-buster'
        update-types: ["version-update:semver-major", "version-update:semver-minor"]

